name: beatmorph
channels:
  - conda-forge
  - defaults
dependencies:
  - python == 3.10
  - pip
  - pip:
    - pandas == 2.0.3
    - numpy == 1.24.4
    - scipy == 1.10.1
    - seaborn == 0.13.2
    - scikit-learn == 1.3.2
    - scikit-image == 0.21.0
    - wave == 0.0.2
    - librosa == 0.10.2.post1

